Emulators:
  - name: "Emulator1"
    packets_per_second: 20000
    packet_size: 2988
    mode: normal
    packet_loss: 0.0
    source_file: "CMakeCache.txt"
    ip: "192.168.1.100"
    port: 8888

  - name: "Emulator2"
    packets_per_second: 15000
    packet_size: 1500
    mode: normal
    packet_loss: 0.1
    source_file: "CMakeCache.txt"
    ip: "192.168.1.102"
    port: 8888

